name: embedded_serialport
description: "`embedded_serialport` is a Flutter package for serial port communication, using Dart FFI to interact with Rust and C libraries."
version: 1.5.4
repository: https://github.com/Zacchaeus-Oluwole/embedded_serialport

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  ffi: ^2.1.2
  path: ^1.9.0
  process: ^5.0.2
  collection: ^1.18.0
  stack_trace: ^1.11.1
  meta: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  plugin:
    platforms:
      linux:
        pluginClass: EmbeddedSerialportPlugin
        ffi: true

  # assets:
  #   - rust_native/librust_serialport.so
